### PR TITLE
V1.2.0 new api

### PR DESCRIPTION
**Pull request by ryukato**
### What kind of change does this PR introduce? 
* [V ] feature

### What is the current behavior? 
* None

### What is the new behavior?
Support following APIs
* create item-token-contract(collection)
* issue service-token 
* query created item-token-contract(collection)
* query issued service-token contract

### CODE REVIEW

**Review by junbae2 — DISMISSED** [review]

**Comment by KIM-KOOKHYUN** [comment]
When createdItemTokenContract is called with (txHash is null), "Invalid txHash - empty not allowed" error is shown.
txHash is not required. If txHash is null, this function have to be completed.

**Comment by KIM-KOOKHYUN** [comment]
### Problem
createItemTokenContract function > CreateItemTokenContractRequest Object 

There is no name value below code. As a result , Request result is Bad Request. You have to add name parameter.
### Code
export class CreateItemTokenContractRequest {
  constructor(
    readonly serviceWalletAddress: string,
    readonly serviceWalletSecret: string,
    readonly baseImgUri: string,
  ) {
    if (RequestParameterValidator.isValidWalletAddress(serviceWalletAddress)) {
      throw new Error(`Invalid serviceWalletAddress - valid pattern: ${RequestParameterValidator.validWalletAddressPattern()}`);
    }
    if (_.isEmpty(serviceWalletSecret)) {
      throw new Error("Empty serviceWalletSecret is not allowed");
    }
    if (!RequestParameterValidator.isValidBaseUri(baseImgUri)) {
      throw new Error(`Invalid baseImgUri of item token - valid pattern: ${RequestParameterValidator.validBaseUriPattern()}`);
    }
  }
}

**Comment by ryukato** [comment]
All issues defects have been fixed.  @KIM-KOOKHYUN I appreciate if you take a look at this again.

**Review by dduck00 — DISMISSED** [review]

**Comment by KIM-KOOKHYUN** [comment]
> All issues defects have been fixed. @KIM-KOOKHYUN I appreciate if you take a look at this again.
### Request
url: '/v1/item-tokens',
      method: 'post',
      data: '{"name":"test","serviceWalletAddress":"tlink14vvjtkr39ssmy9qrhv7egrxw8kg5ylpj6l07r8","serviceWalletSecret":"EM614KYzBK7QrVpvL07QTDiB6uluMv77XbW8d3V2sKo=","baseImgUri":"https://line-objects-dev.com/blab-qa/"}',
      headers: [Object],
      baseURL: 'https://test-api.blockchain.line-beta.me',
### Response
 response: {
      status: 400,
      statusText: 'Bad Request',
      headers: [Object],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    }
### Comment
Bad Request. Other requests are working well.

**Review by KIM-KOOKHYUN — APPROVED** [review]
All isssues have been resolved.

**Review by dduck00 — APPROVED** [review]

**Pull request merged**
